services:
  webapp:
    build: .
    command: gunicorn bulletinstantanee.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/app
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - dbapp

  dbapp:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/


  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - webapp
volumes:
  postgres_data:
