services:
  webapp:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

  dbapp:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
